### PR TITLE
[PluginPresets] fix custom labels

### LINKED ISSUE #62: Custom Preset plugin
### Discussed in https://github.com/easepick/easepick/discussions/61

<div type='discussions-op-text'>

<sup>Originally posted by **pallardino** May 14, 2022</sup>
An other question for customising preset-plugin. 

- First, I have tried to customise labels to put it in French. According to the documentation I passed a list of string, but unfortunately I got the following error from my js console : 
`TypeError: this.options.customLabels.forEach is not a function. (In 'this.options.customLabels.forEach(((t,e)=>{this.options.customPreset[t]=s[e]}))', 'this.options.customLabels.forEach' is undefined)`
- Second, I don't really understand how I can define your own ranges. According to the documentation I have to pass an object, but which object ? For exemple, I would like delete all predefined range and create a custom range for a year. 

Capture d’écran 2022-05-13 à 10 21 44 PM

Thanks in advance
 </div>

### PR DESCRIPTION
**Pull request by nuernbergerA**
Hey @wakirin!

This is a JS problem because 2 objects (options + plugin-options) [get merged](https://github.com/easepick/easepick/blob/e35e8d22b3cf9f8ddeb4fe8f1fcb11a08026a205/packages/base-plugin/src/index.ts#L20) and turn arrays into objects

So we turn the object back into an array

Cheers Adrian

---
Fixes #62

### CODE REVIEW

**Comment by wakirin** [comment]
The issue will show up again if the user provides `customPreset` without `customLabels`
I plan to do it differently, we won't be able to use `customPreset` and `customLabels` at the same time.
So `customLabels` would be for when the user needs to use the default preset but with a different language.
And `customPreset` for when you want to use your own preset ranges (including button text).

**Comment by nuernbergerA** [comment]
### Change just the labels for the default ranges
This is only possible with this PR
```js
{
    PresetPlugin: {
        customLabels: ['1st', '2nd']
    }
}
```
image

### Replace default ranges and define my own
This is possible without this PR
```js
{
    PresetPlugin: {
        customPreset: {
            'im the label': [new Date(), new Date()]
        },
    }
}
```
image

If `customPreset` is not empty `customLabels` will be ignored.

**Comment by Meazem** [comment]
Obrigado

**Comment by Meazem** [comment]
Obrigado

**Pull request merged**
